ga:
  prediction:
    timeFrame: 24
    timeUnit: HOURS
  phenotype:
    maximalPhenotypeAge: 5
    genotype:
      gene:
        min: 0
        max: 1000
  evolution:
    generations: 1000

quarkus:
  application:
    name: airq-ga
  datasource:
    db-kind: postgresql
    username: postgres
    jdbc:
      url: jdbc:postgresql://10.1.1.50:5432/warehouse
    reactive:
      url: postgresql://10.1.1.50:5432/warehouse

mp:
  messaging:
    incoming:
      data-enriched:
        connector: smallrye-kafka
        topic: data.enriched
        value:
          deserializer: org.apache.kafka.common.serialization.StringDeserializer
        key:
          deserializer: pl.airq.common.kafka.TSKeyDeserializer
    outgoing:
      phenotype-created:
        connector: smallrye-kafka
        topic: phenotype.created
        value:
          serializer: org.apache.kafka.common.serialization.StringSerializer
        key:
          serializer: pl.airq.common.kafka.SKeySerializer

kafka:
  group:
    id: airq-ga
  bootstrap:
    servers: 10.1.1.51:9092
